# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.clone("git@github.com:HolyLab/RFFT.jl.git"); Pkg.checkout("FixedSizeArrays")'
  - julia -e 'Pkg.build("BlockRegistration"); Pkg.test("BlockRegistration")'
#   - julia --check-bounds=yes -e 'using BlockRegistration; pth = LOAD_PATH[end]; include(joinpath(splitdir(pth)[1], "test", "runtests.jl"))'
