# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email: false
addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - pkg-config
      - hdf5-tools
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("BlockRegistration")'
  # Because we circumvent Pkg.test, we have to install test dependencies manually
  - julia -e 'cd(Pkg.dir("BlockRegistration","test")); if isfile("REQUIRE") reqs = readlines("REQUIRE"); for r in reqs Pkg.add(chomp(r)) end; end'
  - julia -e 'cd(Pkg.dir("BlockRegistration","test")); use_cuda=false; include("runtests.jl")'
